### ISSUE TITLE
Optional catch-all segments

### ISSUE THREAD

**Issue by cvolant** [svobik7/next-roots#108]
Hi !
Thank you for this project. I wondered if I would need to make next-translate-routes compatible with the app router, but it seems that your solution is better suited for this. I am currently trying it on our migration attempt.
We would need catch-all and optional catch-all segments though, and it seems to not be supported yet (at least, the types are not generated correctly). Would it be possible ?

**Comment by svobik7** [comment]
Hi @cvolant,

that is actually a good question. I guess I forgot about catchAll and optional route types. I am not 100% sure but I assume they are not supported right now. Have you tried?

Unfortunately I dont have much time following two weeks to dig deeper into that. But from my quick observation it could be possible to just update regexp in`formatDynamicSegments` so double brackets [[]] and three leading dots are optionally stripped out.

Would you mind/have a time to create PR that?

**Comment by svobik7** [comment]
Hi @cvolant, I added some tests in new 3.2.1 version and it seems working with catch all routes. I am closing this for now. Feel free to test it and open new issue if any specific use-case does not work for you. Thank you.
