### ISSUE TITLE
Question about language detection

### ISSUE THREAD

**Issue by obrassard** [svobik7/next-roots#111]
Hi @svobik7, sorry for opening an issue for a question 😅 

We are considering using `next-roots` as a replacement to our current i18n solution, with which we had several problems. 
I am wondering if there would be a way to support language detection while using next-roots.

For instance, if a new user navigates to `mywebsite.com/blog` and the locale of the browsers user is `fr_CA` we would like to make a redirection to `mywebsite.com/fr/blogue`.  My first guess would be to create a custom Next middleware for that, but we would have to find the corresponding url in another language, as defined in the i18n.ts files. Do you think this is something easy to achieve ?

Thank you for your help !

**Comment by svobik7** [comment]
Hi @obrassard 

I guess it is better to handle this in a root [...catchAll] route. In that way it will do the lang detection and route parsing only after non of existing routes were matched. 

From top of my head I would do sth like this in [...catchAll]:

```ts
// parse given catchAll slug (it is array)
const [slugLocale, ...slugTail] = catchAll

// remove locale if provided
const slugParts = schema.locales.includes(slugLocale) ? slugTail : catchAll

// create string slug
const slug = catchAll.join('/')

// find route that matches the slug
const matchedRoute = schema.locales.reduce((acc, locale) => acc || router.getRouteFromHref(`${locale}/${slug}`))

// throw 404 when slug is really invalid
if(!matchedRoute) {
  notFound();
}

// Detect user's preferred language e.g. by using https://www.npmjs.com/package/accept-language

acceptLanguage.languages(schema.locales);

const userLanguage = acceptLanguage.get(headers['accept-language');

const routeHref = router.getHref(matchedRoute.name, {locale: userLanguage})

```

Would you mind to test it on your end please? Note that proposed solution is more like blueprint and some code adjustment is needed (missing imports, ...).

If it works we can add it to the package as some helper method.

**Comment by obrassard** [comment]
@svobik7 Here is a basic solution usgin a middleware, to accomplish what I had in mind. There's certainly room for improvement, but I think it's a good start !

**middleware.ts**
```ts
import acceptLanguage from "accept-language";
import { Router, schema } from "next-roots";
import { NextRequest, NextResponse } from "next/server";

export function middleware(request: NextRequest) {
    // Check if this is a new session
    const cookie = request.cookies.get('visitor')
    if (cookie?.value) {
        return NextResponse.next();
    }

    // Get user language from browser
    acceptLanguage.languages(schema.locales);
    const userLanguage = acceptLanguage.get(request.headers.get('accept-language')) ?? schema.defaultLocale;

    const router = new Router(schema)
    const fullPath = request.nextUrl.pathname;
    const currentLocale = router.getLocaleFromHref(fullPath)

    // If the user is already on the correct locale, skip redirect
    if (currentLocale === userLanguage) {
        return NextResponse.next();
    }

    // Get the route that the user is trying to access
    const matchedRoute = router.getRouteFromHref(fullPath)
    if (!matchedRoute) {
        return NextResponse.next();
    }

    // Get the route href for the user's language
    const path = removeLocalePrefix(fullPath);
    const dynamicSegments = extractDynamicSegments(path, matchedRoute.name);
    const routeHref = router.getHref(matchedRoute.name as any, { locale: userLanguage, ...dynamicSegments })

    // Redirect the user to the correct locale
    const response = NextResponse.redirect(new URL(routeHref, request.nextUrl.origin));
    response.cookies.set({
        name: 'visitor',
        value: 'true',
        path: '/',
    })

    return response;
}

export const config = {
    // Skip all paths that should not be internationalized
    matcher: ['/((?!api|_next|.*\\..*).*)']
};

// Helper functions 

function extractDynamicSegments(url: string, routeName: string) {
    const dynamicSegments: Record<string, string> = {};
    const schemaParts = routeName.split('/');
    const urlParts = url.split('/');
    const dynamicRegex = /^\[\w+\]$/
    for (let i = 0; i < schemaParts.length; i++) {
        if (schemaParts[i].match(dynamicRegex)) {
            const paramName = schemaParts[i].slice(1, -1);
            dynamicSegments[paramName] = urlParts[i];
        }
    }
    return dynamicSegments;
}

function removeLocalePrefix(url: string, locales = schema.locales) {
    const urlParts = url.split('/');
    if (locales.includes(urlParts[1])) {
        urlParts.splice(1, 1);
        return urlParts.join('/');
    }
    return url;
}
```

**Comment by svobik7** [comment]
Hi @obrassard,

thank you for your suggestion. I still think that it is possible and probably better to handle it in [[...catchAll]] so that we do not need to track if cookie exists and try to find proper route only when nothing is matched.

Please feel free to check this https://github.com/svobik7/next-roots/pull/112 where I tried to implement what was requested with catchAll route.

For me it works like this:
1. My browser preferred language is Czech = "cs"
2. I visit http://localhost:3000/blogs/joe-black/how-to-find-your-first-gold-treasure which is english dynamic route without locale prefix
3. I am redirected to http://localhost:3000/cs/blogy/joe-black/jak-najit-svuj-prvni-zlaty-poklad which is Czech alternative to that

I guess that is what you need right? Please let me know if you see any issues with that solution. Then I will probably put it to the readme as an example how to handle those cases.

Thank you.

**Comment by obrassard** [comment]
It seems a good way to implement language detection. 

Looking at your example I realize that when I tested catch all segments I had not used double brackets `[[...catchAll]]` and that's probably why it didn't work.

The only drawback with this approach is that it wouldn't work well in the case where the default locale is not prefixed (which is my case), and that's the reason why I needed to use a cookie. 

We also wanted to redirect new users who had clicked on a link to a page of our website in another language to be redirected to the same page in their preferred language.

But overall, I think your example is good for a basic case

**Comment by svobik7** [comment]
Hi @obrassard, I see in your case where you need no default locale prefix there is probably only one way how to do that and that is the middleware. I was thinking about adding some helper methods to package itself but as there can be even other cases where our middleware/catchAll wont be suitable I decided to not include any helpers directly to package but add multiple examples.

Therefore I added:

- `examples/basic` folder which includes the initial example
- `examples/with-preferred-language-catchall` folder that includes redirection to preferred language using catchall
- `examples/with-preferred-language-middleware` folder that will demonstrate your approach but for now is empty

Could you please add your way to that last folder? You can just copy-paste sources in `example/with-preferred-language-catchall` and just update it based on your final solution?

**Comment by obrassard** [comment]
Hi @svobik7, I’ll try to do this next week ! Thank you :)

**Comment by obrassard** [comment]
@svobik7 Here's the new example : https://github.com/svobik7/next-roots/pull/116

**Comment by svobik7** [comment]
Thank you @obrassard for your great work :-) I have just merged your code.
