### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by levipadre** [svobik7/next-roots#114]
Hi,

Is this something I can do with next-roots? It would be a life-saver if it so.
https://github.com/vercel/next.js/discussions/54467

I hope it's clear, but I'm happy to give you more details.

**Comment by svobik7** [comment]
Hi @levipadre, unfortunately that is different use case that is not covered by next-roots. Next-roots works better with file-based i18n (/en/..., /fr/..., /cs/...)

**Comment by levipadre** [comment]
Understand, thank anyway.
