### ISSUE TITLE
question regarding a possible --watch option

### ISSUE THREAD

**Issue by advancedtw** [svobik7/next-roots#133]
Since we are working in a different directory than the app dir, nextjs obviously will not know about the latest changes  Have you considered adding a ```--watch``` option to the cli so esbuild can regenerate on file changes? 
thank you!

**Comment by advancedtw** [comment]
actually it seems some changes are picked up, even hmr works for the most part. Rebuilding is only needed when we create new routes. am I correct ?

**Comment by svobik7** [comment]
Hi @advancedtw, 

> actually it seems some changes are picked up, even hmr works for the most part. Rebuilding is only needed when we create new routes. am I correct ?

yes, that is correct. As generated routes are just simple wrappers the HMR works.

But I like the idea about running in `—watch` mode in dev. Actually it should not be that hard to implement.

I will check it next week if I have a time 🙂

**Comment by svobik7** [comment]
I had a moment and it was easy one. Feel free to test ‘yarn next-roots -w` in new version
