### ISSUE TITLE
Source folder wiped completely when roots script runs into error

### ISSUE THREAD

**Issue by kimskogsmo** [svobik7/next-roots#144]
Hi, 

First of all, thanks for the amazing package. I have gotten it to work on a sample project and I was going to implement it on a new more serious project today. I tried to setup next-roots with the dest directory as /app, so I can use RSC. Also, I use npm in this project (if it matters).

My folder structure is/was like so: 

```
...
src
> app
>> _routes
>>> api
>>> [uid]
>>> page.tsx
>>> ...
> components
> lib
...
```

I moved all my previous app content into the app/_routes folder and then I ran the roots script. Upon which point I get this error:
`Error: ENOENT: no such file or directory, copyfile 'C:\Projects\site\src\app\_routes\api\revalidate\route.js' -> 'C:\Projects\site\src\app\en\api\revalidate\route.js'`. In hindsight, I probably should have kept /api in the app folder, not _routes folder.

Anyway, after the script failed, everything in app/_routes is gone, in other words, all of my original files and folders. If I didn't have a git history I guess there would be no way to get the files back.

I figured I'd raise an issue about it. Some people set up projects and add git later on, in their case, this sort of result from a failed script would be really unfortunate. Maybe a warning is in order in the Getting started guide, to let people know they should back up their files first or make a commit or something.

Anyway, in my case, I have frequent commits so it was no problem. Just a thought.

Thanks again for the great package! Wish vercel would implement something like this into next.

**Comment by svobik7** [comment]
Hi @kimskogsmo,

thank you for pointing this out. Relevant info was added to README.md.

In your case I would recommend to use [RSC config approach](https://github.com/svobik7/next-roots#how-to-keep-original-routes-within-app-folder-to-support-rsc) so that your original routes are kept in `app/_roots` and translated in `app/(routes)`. Doing that only `app/_roots` should be wiped out during generation (even failed one).

**Comment by svobik7** [comment]
Hi @kimskogsmo could you please post your results here? Was my suggestion helpful? So that other can benefit from that. Thank you.

**Comment by kimskogsmo** [comment]
@svobik7 sorry, thought I did. That approach worked great for me! Thanks!
