### ISSUE TITLE
How to Handle Dynamic Slugs with Translated Slugs?

### ISSUE THREAD

**Issue by orhancelik1** [svobik7/next-roots#163]
**Problem:**
I am working on a project that involves dynamic slugs (such as cities, product pages, or articles). Your docs included some dynamic slug examples but they are not translated like: author names or id's. But what should i do when i need to translate them also? most use cases for articles page slugs.

**Comment by svobik7** [comment]
Hi @orhancelik1,

dynamic slugs should be handled either by `generateStaticParams` if you want to pre-generate pages in build time or using `getServerSideProps` to handle everything in runtime. Or combination to gain more granular control.

You can check basic example where you can find `blogs/[author]/[article]/page.tsx`. In that file I am pregenerating dynamic slugs thanks to `pageLocale` that is injected by next-roots.

Let me know if it helps.

https://github.com/svobik7/next-roots/blob/master/examples/basic/src/routes/blogs/%5Bauthor%5D/%5Barticle%5D/page.tsx

**Comment by orhancelik1** [comment]
Thank you so much @svobik7 i translated [slug] fields but i faced new issue i have localeSwitcher in my header module i cannot get translated url. I used dynamic get href like this:

`js 
   const href = router.getHref("/cities/[city]", {
    locale: "tr",
    city: "london",
  });`
  i gives translated '/cities' path but it does not return me translated 'london'
  **my goal:** example.com/tr/sehirler/londra
  **it returns:** example.com/tr/sehirler/london

**Comment by svobik7** [comment]
Hi @orhancelik1, did you update your roots router by running `yarn next-roots` after `cities/[slug]` root was created?

**Comment by orhancelik1** [comment]
yes, it also creates fetch issue i think, when i change the language and navigate to homepage using next/link data not fetching until i refresh the page.

**Comment by orhancelik1** [comment]
yes i did but i should send translated city instead of english one that was my mistake. 
like this: `const href = router.getHref("/cities/[city]", { locale: "tr", city: "londra", });`
