### ISSUE TITLE
Type error at build time

### ISSUE THREAD

**Issue by CarlosEduardoBotero** [svobik7/next-roots#177]
### env
"next": "14.0.4",
"next-roots": "^3.4.1"

### Problem
When I built locally, it fails with this error:

```
Type error: Type 'OmitWithTag<{ locale: RouteLocale; params: any; } & { children?: ReactNode; },
 keyof LayoutProps, "default">'

 does not satisfy the constraint '{ [x: string]: never; }'.
  Property 'locale' is incompatible with index signature.
    Type 'string' is not assignable to type 'never'.
      Type 'string' is not assignable to type 'never'.
```

![next-roots-build-error](https://github.com/svobik7/next-roots/assets/84403687/d6bccba2-676c-4c50-a9e9-b6f1dec36829)

It also fails when this is build on Vercel, this appears in logs:

```
<html>
<body>
<!--StartFragment-->
19:59:49.314 | yarn next-roots
19:59:49.618 | yarn run v1.22.17
19:59:49.646 | $ /vercel/path0/node_modules/.bin/next-roots
19:59:49.756 | next-roots - generation done in: 35.505ms
19:59:49.760 | Done in 0.15s.
19:59:50.631 | ▲ Next.js 14.0.4
19:59:50.632 |  
19:59:50.633 | Creating an optimized production build ...
19:59:57.336 | ✓ Compiled successfully
19:59:57.337 | Linting and checking validity of types ...
20:00:01.900 | Failed to compile.
20:00:01.900 |  
20:00:01.901 | app/_roots/layout.tsx
20:00:01.901 | Type error: Layout "app/_roots/layout.tsx" has an invalid "default" export:
20:00:01.901 | Type "{ locale: RouteLocale; params: any; } & { children?: ReactNode; }" is not valid.
20:00:01.901 |  
20:00:01.968 | Error: Command "npm run build" exited with 1

<!--EndFragment-->
</body>
</html>
```
![image](https://github.com/svobik7/next-roots/assets/84403687/c3258810-787d-47d7-a38c-b91079888971)

The type that I´m using for the **RootLayout** is:

```
export type RootLayoutProps = PropsWithChildren<{
  locale: RouteLocale;
  params: any;
}>;
```

I followed [How to keep original routes within APP folder to support RSC?](https://github.com/svobik7/next-roots#how-to-keep-original-routes-within-app-folder-to-support-rsc) path.

if you need more context this is the [repo](https://github.com/CarlosEduardoBotero/cebv-portfolio-v1/tree/main/app).

btw I was wondering when I run the command `yarn next-roots` should I commit the generated folders?

Great job I´m loving this library!

**Comment by svobik7** [comment]
Hi @CarlosEduardoBotero,

thanks for pointing this out. It might be some type inconsistency between next@14 and next-roots. But needs to be investigated a big deeper.

I will be able to dig into it in January at the earliest.

But in the meantime, could you please verify that the error disappears when you downgrade to next@13?

Thank you.

**Comment by CarlosEduardoBotero** [comment]
Hi @svobik7!

I ran the command `npm i next@13`

It downgraded to **next@13.5.6**

But I'm still getting a _type error_  at the _page.tsx_ file.

![image](https://github.com/svobik7/next-roots/assets/84403687/3d00cdad-362d-4067-b9d8-669994254a23)

**Comment by Jon1VK** [comment]
The problem you have is that Next.js is type checking all page.tsx, layout.tsx etc. files inside app folder at build time to comply with Next.js restrictions for these files.

You have two ways to remove the error:
1. Disable build time TS check [https://nextjs.org/docs/app/api-reference/next-config-js/typescript](https://nextjs.org/docs/app/api-reference/next-config-js/typescript)
2. Move your next-roots page template files outside of the app folder for example in a folder named _app.

**Comment by svobik7** [comment]
Agree with @Jon1VK, it is issue with Next.js that it type-checks and lints every `page.tsx` file in app folder even those in private folders (prefixed with `_`). I would suggest the same as @Jon1VK to move your _roots folder to sth like `src/roots`.
