### ISSUE TITLE
CSS/favicon issue when integrating with app created by `npx create-next-app`

### ISSUE THREAD

**Issue by zto-sbenning** [svobik7/next-roots#201]
Hello,

First of all, a big thank you for this awesome library! I come from https://github.com/vercel/next.js/discussions/18485 and it's crazy that the accepted answer was not yours!

I tried to implement the step in your Readme, but I have some issues.

This is my `roots.config.js`:
```
const path = require('path')

module.exports = {
    originDir: path.resolve(__dirname, 'src/roots'),
    localizedDir: path.resolve(__dirname, 'src/app/(routes)'),
    locales: ['fr', 'en'],
    defaultLocale: 'fr',
    prefixDefaultLocale: false, // serves "fr" locale on / instead of /fr
}
```

This my (generated) app structure:
- src
    - app
        - (routes)
            - (fr)
                - actualites
                    - page.tsx
                - layout.tsx
                - page.tsx
            - en
                - news
                    - page.tsx
                - layout.tsx
                - page.tsx
        - favicon.ico
        - globals.css
        - robots.ts
        - sitemap.ts
    - roots
        - actualites
            - i18n.ts
            - page.tsx
        - layout.tsx
        - page.tsx

The structure looks really fine.
But when I access `/` or `/en` on the browser, the `globals.css` file is not loaded (it is however visible in the network inspection tab as `layout.css`). The favicon.ico file is not loaded nor requested.

In `src/roots/layout.tsx` the `globals.css` file is initialy imported like so:
`import "./globals.css";`

Witch obviously does not work.

I tried importing it with `import "@/app/globals.css";` but without success.
For reference, my tsconfig.json file includes:
```
    "paths": {
      "@/*": ["./src/*"]
    }
```

I suspect the issue is on my side, but I can't point out where it is in my config/structure.

Any help will be greatly appreciated!

**Comment by zto-sbenning** [comment]
Sorry for my dummy mistake!

It works fine with: `import "@/app/globals.css";` but I just missed to add: `"./src/roots/**/*.{js,ts,jsx,tsx,mdx}"` in the `tailwind.config.ts` ...

For the favicon it might have been a cache issue. It works well now.

Again, sorry for aving polluted your issues with this. Maybe it would be usefull however for others..

**Comment by svobik7** [comment]
No worries @zto-sbenning, glad to hear you solved your issue 👍
