### ISSUE TITLE
next-roots - Given rewrite is not a page route rewrite.

### ISSUE THREAD

**Issue by juliomuhlbauer** [svobik7/next-roots#211]
![image](https://github.com/svobik7/next-roots/assets/53458125/4da8a34f-e8cc-44c7-b40d-703af8e34462)

**Comment by svobik7** [comment]
Hi @juliomuhlbauer could you please provide minimal repo? Or at least list your origin dir files?

**Comment by juliomuhlbauer** [comment]
As for now I will use Paraglide from Inlang. If something changes I will open another issue. Thanks!
