### ISSUE TITLE
Is there a downside of using Inlang compared to next-roots?

### ISSUE THREAD

**Issue by juliomuhlbauer** [svobik7/next-roots#212]
https://inlang.com/m/osslbuzt/paraglide-next-i18n/

They use a middleware approach, but their approach affects the SEO?

**Comment by svobik7** [comment]
I haven't tried InLang lib yet but I don't think that SEO is anyhow harmed when using it. Honestly it seems like a great library offering you a solution even to translate messages.

🔎 In general using middleware approach brings some issues straight away you need to deal with. But it seems they are aware of them, alredy solved some or put them on their roadmap. See my point bellow.

🪲InLang issues (published on their web):

- output: static isn't supported yet.
- Evaluating messages in module scope always renders the source language.
- Server actions that aren't inside a .tsx file will always read the default language unless setLanguageTag(()=>headers().get("x-language-tag")) is called at the top of the file.

🧭 InLang Roadmap to 1.0
- Static Export support
- Simplify Setup
- Cookie & Domain Routing Strategies

➡️ Using next-roots:
- static export works out of the box IMO as lacalized pages are pre-generated
- there is no runtime needed to re-route localized alias to target page
- server actions language should work out-of-box thanks to pregenerated pages

---

🍀 Anyway I am not advocating next-roots here. Based on the size of InLang community, their roadmap and ecosystem they provide it seems like a more mature library with more features.

So if static export and server action language workaround does not bother you (they will probably solve it anyway in 1.0) and you can gain from they ecosystem (especially messages translation) go for InLang 👍

**Comment by juliomuhlbauer** [comment]
Thanks a lot! I think I will go for Inlag because of ecosystem and easier setup. But next-roots is a amazing project!
