### ISSUE TITLE
Feature Request: Allow page and layout to export `viewport` and `generateViewport`

### ISSUE THREAD

**Issue by zto-sbenning** [svobik7/next-roots#271]
Hi,

From the Next documentation : https://nextjs.org/docs/app/api-reference/functions/generate-viewport layouts and pages should be able to export a viewport object or the generateViewport function.

For now, `next-roots` does not add those exports in the generated code.

I can work on a PR for this. Is it OK for you ?

Cheers

**Comment by svobik7** [comment]
Thank you 👍 should be now included in 3.11.0
