### ISSUE TITLE
Doesn't generate 'pages' directory

### ISSUE THREAD

**Issue by brerdem** [svobik7/next-roots#30]
When I run `yarn dev` it briefly generates 'pages' directory and removes it. Then the compiler exits with the error `Error: > Couldn't find a `pages` directory. Please create one under the project root`

**Comment by svobik7** [comment]
Which version are you using? Can you provide me with your package.json?

**Comment by brerdem** [comment]
Sure

>   "scripts": {
    "dev": "yarn next-roots && next dev",
    "build": "yarn next-roots && next build",
    "start": "next start"
  },
  "dependencies": {
    "@zeit/next-less": "^1.0.1",
    "colors": "^1.4.0",
    "google-maps-react": "^2.0.6",
    "isomorphic-unfetch": "^3.0.0",
    "less": "^3.11.1",
    "next": "9.4.0",
    "next-roots": "^1.0.5",
    "nookies": "^2.3.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "uikit": "^3.5.4"
  }
}

**Comment by svobik7** [comment]
I created new branch with example containing your package setup. Everything works well on my machine `MacOs Catalina + Node 12.16.0`
 
1. Clone this branch -> https://github.com/svobik7/next-roots/tree/issues/30-does-not-generate-pages
2. Navigate to example directory `cd example` 
3. Run `yarn dev`

Could you please test it in your env?

**Comment by svobik7** [comment]
Also how does your `roots.config.js` look like?

**Comment by brerdem** [comment]
> Also how does your `roots.config.js` look like?

Here is my `roots.config.js`. By the way I put only a single root to see if it's working

> module.exports = {
    locales: ['tr', 'en'],
    defaultLocale: 'tr',
    defaultSuffix: '',
    schemas: [
        {
            root: '*',
            metaData: { title: 'Next Roots', background: 'grey' },
        },
        {
            root: 'home',
            pages: [{ locale: '*', path: 'index', alias: '/', suffix: '' }],
        },
        {
            root: 'about-us',
            pages: [
                { locale: 'tr', path: 'hakkimizda' },
                { locale: 'en', path: 'about-us' },
            ],
            params: { token: 'p1' },
        },

    ],
}

**Comment by svobik7** [comment]
There are two main issues with you `roots.config.js`.

1. Wrong `general root` config
>{
root: '',
metaData: { title: 'Next Roots', background: 'grey' },
},

If you want to use `general root` for sharing meta data it has to be `root: '*'`

```js
{
   root: '*',
   metaData: { title: 'Next Roots', background: 'grey' },
}
```
2. Wrong `general page` config
>{
root: 'home',
pages: [{ locale: '', path: 'index', alias: '/', suffix: '' }],
},

If you want to use `general page` for sharing page config among all locales it has to be defined with `locale: '*'`:

```js
{
   root: 'home',
   pages: [{ locale: '*', path: 'index', alias: '/', suffix: '' }],
},
```

@brerdem you can find example with your config (fixed of issues) in this branch -> https://github.com/svobik7/next-roots/tree/issues/30-does-not-generate-pages

Feel free to test it on your machine and let me know.

**Comment by brerdem** [comment]
@svobik7 The asterisks seem to be removed when I paste the code here. Here's the correct one. 

` {
            root: '*',
            metaData: { title: 'Next Roots', background: 'grey' },
        },
        {
            root: 'home',
            pages: [{ locale: '*', path: 'index', alias: '/', suffix: '' }],
        },
        {
            root: 'about-us',
            pages: [
                { locale: 'tr', path: 'hakkimizda' },
                { locale: 'en', path: 'about-us' },
            ],
            params: { token: 'p1' },
        },
`

And here is the error. I also tried to manually create pages folder after getting this error but it's also deleted when I run `dev` or `build`.

![image](https://user-images.githubusercontent.com/778976/87520033-16977580-c68b-11ea-8503-2e37d471d036.png)

I will try with the one you provided to me. Thanks!

**Comment by svobik7** [comment]
Ok, let me know then. If it wont work then create a minimal repo with your files so I can investigate further.

**Comment by brerdem** [comment]
@svobik7 you can find the repo at https://github.com/brerdem/next-roots-example.git

**Comment by svobik7** [comment]
I see, you do not use TypeScript. Therefore you have to set following in your `roots.config.js`:

```js
module.exports = {
  extRoots: ['.js'],
  // ... other config
}
```

Also I noticed that you use relative paths in your roots like `../components/global/config` this wont work once pages are generated. It is because generated path to pages will be one level deeper `/tr/...` so it is necessarily to use path relative to your base folder. 

```js
// this is required config in your jsconfig.json to handle paths relative to baseUrl
{
  "compilerOptions": {
    "baseUrl": "."
  }
}
```

Anyway I created PR on your repo with working application.
Feel free to check it here: https://github.com/brerdem/next-roots-example/pull/1

**Comment by brerdem** [comment]
Thanks @svobik7 it's working right now
