### ISSUE TITLE
Next.js 15 breaking change to params types

### ISSUE THREAD

**Issue by Jon1VK** [svobik7/next-roots#302]
[Async Request APIs (Breaking Change)](https://nextjs.org/blog/next-15#async-request-apis-breaking-change)

APIs that rely on request-specific data, such as headers, cookies, params, and searchParams, are transitioned to be asynchronous.

This changes how params should be typed in this package.

For example PageProps should now for Next.js 15 to be defined as

```ts
type PageProps<TParams = void> = TParams extends void ? {
    pageHref: string;
} : {
    pageHref: string;
    params: Promise<TParams>;
}
```

**Comment by Jon1VK** [comment]
The templates are also problematic now since the params should be awaited before they are used. [This line](https://github.com/svobik7/next-roots/blob/599008f80f99d7d3ee5c0e64592cc3beb1e1e34a/src/cli/templates/page-tpl.ts#L45) for example uses the params before params are awaited.

**Comment by Jon1VK** [comment]
I don't really know what would be the optimal solution here...

One solution could be that next-roots package awaits the promised params in the entrypoint page.tsx file and passes the resolved params to the origin component exactly the same as it has passed them until now. But that is not always what the developer wants. For example one might want to pass the promised params down the component tree to some leaf component, where the promised params would be awaited and the leaf component would be wrapped with a Suspence boundary. That would allow the page to be rendered synchronously upto that leaf component.

If the params are not awaited at the entrypoint by next-roots package, then next-roots package would need to give up of creating the pageHref in the page.tsx entrypoint (because params are needed to generate the pageHred) and just pass the locale to the origin component.

I have also been thinking if AsyncLocalStorage could be used instead of Router instance for passing the locale and/or other next-roots spesific page context to the child components to allow for real separation of contexts between page generations. But that idea is already out of scope of this issue and is just an idea maybe worth of researching in another issue.

**Comment by svobik7** [comment]
Hi @Jon1VK,

I was thinking about this and dropping compilation of pageHref actually makes sense.

We can store promised params in StaticRouter together with not yet compiled page href.

Then only when developer calls "getPageHref" or similar method from Router class we can await params.

It will definitely bring a breaking changes as all those methods become asynchronous. But IMO that is ok as it follows nextjs 15 relevant changes.

I already created V4 PR where I solved some long term issues and planning to incorporate even this change.

Do you think you would havevtime to contribute to this initiative?

**Comment by Jon1VK** [comment]
I would have now extra time to contribute to this, if you have not started already incorporating the changes.

**Comment by Jon1VK** [comment]
I added a draft PR, which implements the required changes to the package code itself but is missing the changes to the examples and to the Readme. We can continue the conversation in the PR.
