### ISSUE TITLE
Different schema generated in local vs prod

### ISSUE THREAD

**Issue by salahzsh** [svobik7/next-roots#319]
Hi, I've been using next-roots for all my projects without any problem (thanks for the work you have put on this package!) but recently after cloning a working project to build another site I found that the schema generated locally is different than the one in production (in Vercel).

I get 9 routes locally but only 5 when deployed so when trying to do get some urls from router I just get the root route '/'

I've been trying to debug but I'm not quite sure how to approach or what to look for in this case.

Any help or guidance on how to debug it or what I might be missing/or what might be the issue?

Routes has been generated properly since I can access them directly typing the url in the browser, is just when trying to getHref or printing the schema that there are some routes missing

Thank you in advance

**Comment by svobik7** [comment]
Can you provide a log from vercel + i18n files for missing routes?
