### ISSUE TITLE
Unused compileHref outputted if no generateMetadata

### ISSUE THREAD

**Issue by jakubjanousek** [svobik7/next-roots#320]
If the original page doesn't contain generateMetadata function, the output still contains (unused) `compileHref` import.

This results in error in our lint check because of `Error: 'compileHref' is defined but never used.  unused-imports/no-unused-imports`.

Workaround is to add an empty generateMetadata function to our page, ie.

```
export async function generateMetadata(_props) {
  return {}
}
```

**Comment by svobik7** [comment]
Hi @jakubjanousek,

that is valid point and will be fixed 👍

However I would highly recommend to exclude generated files from being linted. As those files should stay untouched you do not need to lint them at all.
