### ISSUE TITLE
How to generate pages outside of locale folders?

### ISSUE THREAD

**Issue by brerdem** [svobik7/next-roots#33]
I'd like to display the same page with different paths without specifying the locale. Say I have `about-us` root, I'd like to bring this page by either `/about-us` or `/hakkimizda`.

**Comment by svobik7** [comment]
This is not possible in `1.x` but has been implemented in `2.x` (yet as experimantal). Feel free to try canary release of 2.0.0.

- Generating pages outside locale folders - https://github.com/svobik7/next-roots/tree/canary#9-migrating-from-1x-to-2x
- There are two easy steps to migrate - https://github.com/svobik7/next-roots/tree/canary#10-experimental

**Comment by brerdem** [comment]
Now I'm getting an error something like this. Could it be something about my configuration?

![image](https://user-images.githubusercontent.com/778976/87906716-dc9fe800-ca6b-11ea-9ac5-d4b93c925625.png)

**Comment by svobik7** [comment]
I see, it is TypeScript typings which is not allowed in plain JS. I am gonna fix it today by option to drop TS completely 👍 thank you

**Comment by svobik7** [comment]
@brerdem could you please try latest `next-root@canary`? There is new option which disables page types generation so that it fixes mentioned error.

```js
// roots.config.js
{
    useTypings: false,
    // ... other configs
}
```

**Comment by brerdem** [comment]
@svobik7 Thanks it's working like a charm right now. You can close it.
