### ISSUE TITLE
Path aliases seem take no effect

### ISSUE THREAD

**Issue by brerdem** [svobik7/next-roots#34]
Whenever I define `alias` for pages I expect to see URL changes with alias value but I couldn't make it work. In the example below I'd like to change the slug to the aliases but nothing happens

```
{
      root: 'about-us',
            pages: [
                {locale: 'tr', path: 'hakkimizda', alias: '/biz'},
                {locale: 'en', path: 'about-us', alias: '/us'},
            ],
 },
```

**Comment by svobik7** [comment]
You do not need to set alias in your case. To have `/tr/biz` and `/en/us` page targeting to `about-us` root you can use following config:

```js
{
      root: 'about-us',
      pages: [
          {locale: 'tr', path: 'biz'},
          {locale: 'en', path: 'us'},
      ],
 },
```

Is that what you want?

---

Aliases were mentioned primarily for aliasing `index` pages like:

```js
{
    root: 'home',
    pages: [
      { locale: '*', path: 'index', alias: '/' }  
    ]
}
```

With above config the page file will be generated at path `/en/index` and route alias will be `/en`.

**Comment by brerdem** [comment]
Basically I want to be free to set any slug no matter where the actual page file is. I don't even want a locale folder like en, fr, de or so, but to be able to inject locale by defining the roots in config.

**Comment by brerdem** [comment]
In #33 you mention it so I'm closing for now. Thanks
