### ISSUE TITLE
Backslash issue

### ISSUE THREAD

**Issue by brerdem** [svobik7/next-roots#38]
Generated pages has backslashes on their import lines as seen on the screenshot below. Thus, it gives `module not found error`

Note: I'm using Windows 10. It works perfectly on MacOSX

![image](https://user-images.githubusercontent.com/778976/88184076-f3486980-cc3a-11ea-8953-08cc59673cd8.png)

**Comment by svobik7** [comment]
@brerdem should be now fixed in `canary` release. Could you test it, please?

**Comment by brerdem** [comment]
@svobik7 It's fixed. Thanks!
