### ISSUE TITLE
Routing from index page

### ISSUE THREAD

**Issue by brerdem** [svobik7/next-roots#39]
I'd like to have a routing from index.js to the corresponding locale's index page at the start. E.g from "/" to "/en". I actually did with next.js's built-in Router API and getServerSideProps but I'm curios if there is an elegant way to do it with next-roots.

**Comment by svobik7** [comment]
There is no next-roots way how to handle initial redirect. I think it is out of scope of this lib.

This feature highly depends on app requirements about how initial locale should be detected (based on cookie, headers, browser language, ...).

Therefore I did not cover it by next-roots. I just provide an example how it can be done easil. You can see It in the example folder. There is IndexRoot which simply redirects to the default language set in schema. Using this simple approach you can be easily redirect to any other desired (detected) locale.

https://github.com/svobik7/next-roots/blob/master/example/roots/index.tsx#L15

**Comment by brerdem** [comment]
Thanks @svobik7 it's been extremely helpful.
