### ISSUE TITLE
Add support to nextjs rewrites

### ISSUE THREAD

**Issue by svobik7** [svobik7/next-roots#45]
Nextjs rewrites should be automatically generated when `as` differs from `href`.

```js
{
  root: 'modules/users/roots/user-view-root', // path-to-root-file
  rootName: 'users/view', // unique id used to find href and as'
  pages: [
    { locale: '*', path: '[username]/index', as: '@:username(\w-.)' }
  ]
}
```

**Comment by thiras** [comment]
Hello. Thanks for this amazing package. The Next community definitely should know more about this project.

Do you plan to implement this issue?

**Comment by svobik7** [comment]
Hello @thiras, thak you for your comment. Since next.js dropped `as` attribute in version 10.0. I have no plans to implement this feature on my own now.

Feel free to create PR 🙂
