### ISSUE TITLE
Vercel build error

### ISSUE THREAD

**Issue by j-sup** [svobik7/next-roots#84]
### env
"next": "13.2.5-canary.16",
"next-roots": "^3.0.5"

### problem

When this is built locally, it is successful. However with this is build on Vercel, this appears in logs:
```
Module not found: Can't resolve './cache/schema' in '/vercel/path0/node_modules/next-roots/dist'
```

Later on in logs, this error for one of the app pages:
```
./app/(en)/(admin)/admin/comments/page.tsx:3:10
16:55:05.628 | Type error: Module '"next-roots"' has no exported member 'Router'.
```

**Comment by svobik7** [comment]
Hi @j-sup, I was not able to reproduce your issue. I tried on latest canary, latest stable and 13.2.5-canary.16 and it worked in every case. Could you please make sure that you are running `yarn next-roots` before the build?

Something like this should be in your package.json:

```json
 "scripts": {
    "roots": "yarn next-roots",
    "build": "yarn roots && next build",
  },
```

**Comment by j-sup** [comment]
> running yarn next-roots before the build

Ah, yes there was the issue. Thanks!
