### ISSUE TITLE
Feature: Add support for parallel routes

### ISSUE THREAD

**Issue by Jon1VK** [svobik7/next-roots#90]
Currently the package does not support [parallel routes](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes). Parallel routes are extremely helpful for designing more complex layouts.

I can help with implementing this functionality since it probably needs only some changes to the [getRoute.ts](https://github.com/svobik7/next-roots/blob/master/src/cli/utils/getRoute.ts) file and some new test cases to confirm the new additions are working properly.

**Comment by Jon1VK** [comment]
P.S. This package has been already extremely helpful. With the support for parallel routes I think this package will be perfect for my use-case.

**Comment by svobik7** [comment]
Hi @Jon1VK, great idea! I saw you PR and looks good, thank you for your contribution 👍 I am just thinking if it makes sense to add parallel routes to example. I will probably update it later.

**Comment by svobik7** [comment]
Sorry for closing - was miss click 😅 I will merge this and publish a new version on Monday once I am back at my comp.
