### ISSUE TITLE
Add support for Route Segment Config for Layouts and Pages

### ISSUE THREAD

**Issue by Jon1VK** [svobik7/next-roots#96]
Add support for Route Segment Config for Layouts and Pages:
```
export const dynamic = 'auto'
export const dynamicParams = true
export const revalidate = false
export const fetchCache = 'auto'
export const runtime = 'nodejs'
export const preferredRegion = 'auto'
```

Good to know: The values of the config options currently need be statically analyzable. For example revalidate = 600 is valid, but revalidate = 60 * 10 is **not.**

See: [https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config)

**Comment by Jon1VK** [comment]
Hi @svobik7, I noticed that Route Segment Config is not supported yet. The functionality is added in the linked PR.

**Comment by svobik7** [comment]
Good job! Thank you 🙂
